CREATE OR REPLACE VIEW V_RESUMEN
(CUENTA,SALDO,SUCUCODIGO,SUCUNOMBRE,
 TIPOCODIGO, TIPONOMBRE,
 MONECODIGO,MONENOMBRE,ACCION,FECHA,IMPORTE)
AS
WITH 
V1 AS (
	SELECT
	  M.CHR_CUENCODIGO       CUENTA,
	  TM.CHR_TIPOCODIGO      TIPOCODIGO,
	  TM.VCH_TIPODESCRIPCION TIPONOMBRE,
	  TM.VCH_TIPOACCION      ACCION,
	  M.DTT_MOVIFECHA        FECHA,
	  M.DEC_MOVIIMPORTE      IMPORTE
	FROM TIPOMOVIMIENTO TM
	JOIN MOVIMIENTO M
	ON TM.CHR_TIPOCODIGO = M.CHR_TIPOCODIGO),
V2 AS (
	SELECT 
		C.CHR_CUENCODIGO CUENTA,
		S.CHR_SUCUCODIGO SUCUCODIGO,
		S.VCH_SUCUNOMBRE SUCUNOMBRE,
		M.CHR_MONECODIGO MONECODIGO,
		M.VCH_MONEDESCRIPCION MONENOMBRE,
		C.DEC_CUENSALDO  SALDO
	FROM MONEDA M
	JOIN CUENTA C ON M.CHR_MONECODIGO = C.CHR_MONECODIGO
	JOIN SUCURSAL S ON C.CHR_SUCUCODIGO = S.CHR_SUCUCODIGO)
SELECT 
  V1.CUENTA, V2.SALDO, V2.SUCUCODIGO, V2.SUCUNOMBRE,
  V1.TIPOCODIGO, V1.TIPONOMBRE,
  V2.MONECODIGO, V2.MONENOMBRE,
  V1.ACCION, V1.FECHA, V1.IMPORTE
FROM V1 JOIN V2 ON V1.CUENTA = V2.CUENTA;



SELECT 
	SUCUCODIGO, SUCUNOMBRE, 
	MONECODIGO, MONENOMBRE,
	ACCION, SUM(IMPORTE) IMPORTE
FROM V_RESUMEN
WHERE SUCUCODIGO = '002'
AND MONECODIGO = '02'
GROUP BY SUCUCODIGO, SUCUNOMBRE, 
	MONECODIGO, MONENOMBRE, ACCION;

	
	
SELECT 
  CUENTA, SALDO, ACCION, SUM(IMPORTE) IMPORTE
FROM V_RESUMEN
WHERE CUENTA = '00100001'
GROUP BY CUENTA, SALDO, ACCION;



WITH 
V1 AS (
	SELECT 
		CUENTA, ACCION, SUM(IMPORTE) IMPORTE
	FROM V_RESUMEN
	WHERE CUENTA = '00100001'
	GROUP BY CUENTA, ACCION)
SELECT
	V1.CUENTA, C.DEC_CUENSALDO SALDO, V1.ACCION, V1.IMPORTE
FROM CUENTA C JOIN V1
ON C.CHR_CUENCODIGO = V1.CUENTA;



	

CUENTA
SALDO
SUCUCODIGO
SUCUNOMBRE
TIPOCODIGO
TIPONOMBRE
MONECODIGO
MONENOMBRE
ACCION
FECHA
IMPORTE



	
	
	